# Clippy configuration for leptos-next-metadata
# Enforces strict linting rules for high-quality code

# Allow some lints that are too strict for our use case
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 8
too-many-lines-threshold = 300
type-complexity-threshold = 250
