# Pre-commit hooks configuration for leptos-next-metadata
# This configuration ensures code quality, formatting, and security checks

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # File checks
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.md$'
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]

      # Security checks
      - id: detect-private-key
      - id: detect-aws-credentials

      # File naming
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # TypeScript/JavaScript hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, css, scss, html, markdown, yaml]
        exclude: "^docs/"
        args: ["--write", "--tab-width=2"]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--ignore", "docs/"]
        exclude: "^docs/"

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: '\.lock$|\.min\.js$'

  # Custom hooks for this project
  - repo: local
    hooks:
      # Rust formatting
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
        always_run: false
        files: \.rs$

      # Rust clippy (with warnings instead of errors for now)
      - id: rust-clippy
        name: rust-clippy
        entry: cargo clippy --all-features
        language: system
        pass_filenames: false
        always_run: false
        files: \.rs$

# Configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: "3.0.0"

# Exclude patterns
exclude: |
  (?x)^(
    target/.*|
    node_modules/.*|
    \.git/.*|
    docs/.*|
    \.cargo/.*|
    \.vscode/.*|
    \.idea/.*|
    .*\.lock$
  )$
