[package]
name = "leptos-next-metadata"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Next.js-style metadata management for Leptos applications with type-safe APIs and blazing-fast OG image generation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/leptos-next-metadata"
homepage = "https://github.com/yourusername/leptos-next-metadata"
documentation = "https://docs.rs/leptos-next-metadata"
keywords = ["leptos", "metadata", "seo", "og-image", "nextjs", "web"]
categories = ["web-programming", "asynchronous", "web-framework"]
readme = "README.md"

[dependencies]
# Core dependencies
leptos = { version = "0.8", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
once_cell = "1.0"
parking_lot = "0.12"
chrono = { version = "0.4", features = ["serde"] }
url = "2.0"
regex = "1.0"
liquid = "0.26"
image = "0.24"
resvg = "0.36"
usvg = "0.36"
fontdue = "0.8"
mime_guess = "2.0"
walkdir = "2.0"

# Optional dependencies
reqwest = { version = "0.11", optional = true, features = ["json"] }
cached = { version = "0.45", optional = true }
lru = { version = "0.12", optional = true }
tempfile = { version = "3.0", optional = true }

[dev-dependencies]
criterion = "0.5"
proptest = "1.0"
mockall = "0.12"
tokio-test = "0.4"
tempfile = "3.0"

[features]
default = ["ssr", "og-images", "file-conventions"]
ssr = ["leptos/ssr"]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
og-images = ["image", "resvg", "usvg", "fontdue"]
file-conventions = ["walkdir", "mime_guess"]
json-ld = ["serde_json"]
caching = ["cached", "lru"]
http = ["reqwest"]
debug = []

[lib]
name = "leptos_next_metadata"
path = "src/lib.rs"

[[bench]]
name = "og_image_generation"
harness = false

[[bench]]
name = "metadata_resolution"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
