# Cargo-deny configuration for dependency management and security

[graph]
# Maximum depth for dependency graph traversal
max-depth = 20

# Allow duplicate dependencies with different versions
allow-duplicates = false

# Allow multiple versions of the same crate
allow-multiple-versions = false

[licenses]
# Allow these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Zlib",
    "0BSD",
    "CC0-1.0",
    "MPL-2.0",
    "MIT-0",
]

# Deny these licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "CDDL-1.0",
    "CDDL-1.1",
    "EPL-1.0",
    "EPL-2.0",
    "CPOL-1.02",
    "Sleepycat",
    "EUPL-1.1",
    "EUPL-1.2",
]

# Allow these specific crates regardless of license
allow-osi-fsf-free = "neither"

# Allow these specific crates regardless of license
# allow = [
#     # Allow specific crates that might have restrictive licenses
#     # but are essential for functionality
# ]

# Deny these specific crates regardless of license
# deny = []

# Allow these specific crates regardless of license
# exceptions = [
#     # Add exceptions here if needed
# ]

[sources]
# Allow these registries
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]

# Deny these registries
deny-registry = []

# Allow these git sources
allow-git = [
    "https://github.com/leptos-rs/leptos",
    "https://github.com/cloud-shuttle/leptos-next-metadata",
]

# Deny these git sources
deny-git = []

# Allow these specific git sources
allow-git-commit = []

# Deny these specific git sources
deny-git-commit = []

[advisories]
# Database to use for security advisories
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]

# Ignore these advisories
ignore = [
    # Add advisory IDs to ignore here
]

# Informational advisories to warn about
informational-warn = [
    "unmaintained",
    "unsound",
    "yanked",
]

# Informational advisories to deny
informational-deny = []

# Severity levels to warn about
severity-threshold = "low"

# Allow these specific advisories
allow = []

# Deny these specific advisories
deny = []

[metadata]
# Minimum Rust version
msrv = "1.70.0"

# Allow these specific crates to have different MSRV
allow-msrv = []

# Deny these specific crates to have different MSRV
deny-msrv = []
