[alias]
# Test aliases
test-all = "test --all-features --workspace"
test-unit = "test --lib"
test-integration = "test --test '*'"
test-doc = "test --doc"
test-features = "test --no-default-features"

# Benchmark aliases  
bench-all = "bench --all-features"
bench-save = "bench --all-features -- --save-baseline"
bench-compare = "bench --all-features -- --baseline"

# Coverage aliases
coverage = "tarpaulin --all-features --out Html --output-dir target/coverage"
coverage-xml = "tarpaulin --all-features --out Xml --output-dir target/coverage"

# Quality aliases
fmt-check = "fmt --all -- --check"
clippy-all = "clippy --all-features -- -D warnings"
audit-check = "audit"

# Build aliases
build-all = "build --all-features"
build-release = "build --release --all-features"
doc-build = "doc --all-features --no-deps"

# Utility aliases
clean-all = "clean && cargo update"
tree-features = "tree --all-features"

# Use faster linker on supported platforms
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Build configuration
[build]
incremental = true

# Environment variables
[env]
CARGO_FEATURE_DEFAULT = "ssr,og-images,file-conventions,macros"